// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Statefalse.Infrastructure.Data;

#nullable disable

namespace Statefalse.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825122613_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Statefalse.Domain.Models.CheckSuiteEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CheckSuiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadBranch")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadSha")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PrAuthorGitHubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrAuthorLogin")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepoFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasNotified")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Conclusion");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("PrAuthorLogin");

                    b.ToTable("CheckSuiteEvents");
                });

            modelBuilder.Entity("Statefalse.Domain.Models.GitHubUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GitHubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalRConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPatToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("GitHubUsername")
                        .IsUnique();

                    b.ToTable("GitHubUsers");
                });

            modelBuilder.Entity("Statefalse.Domain.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PrNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("RecipientGitHubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Repo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientGitHubId", "CreatedAt");

                    b.HasIndex("RecipientGitHubId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Statefalse.Domain.Models.PullRequestEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("AuthorGitHubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseBranch")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Conclusion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Draft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraInfo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadBranch")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadSha")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCommentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCommentBody")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCommentBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCommentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastReviewFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastReviewLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MergeableState")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PrNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReviewApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriberIds")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasNotified")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorLogin");

                    b.HasIndex("PrNumber");

                    b.HasIndex("Status");

                    b.ToTable("PullRequestEvents");
                });

            modelBuilder.Entity("Statefalse.Domain.Models.PunishmentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CulpritGitHubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CulpritLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasNotified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CulpritLogin");

                    b.HasIndex("OccurredAt");

                    b.ToTable("PunishmentEvents");
                });

            modelBuilder.Entity("Statefalse.Domain.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GitHubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("GitHubId", "RevokedAt", "ExpiresAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Statefalse.Domain.Models.WorkflowRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("GitHubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeadBranch")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadSha")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetGitHubIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId");

                    b.HasIndex("RunId");

                    b.HasIndex("Status");

                    b.ToTable("WorkflowRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
